### PR TITLE
Added string_util_pkg.is_str_integer

### PR DESCRIPTION
**Pull request by mjhasbach**

### CODE REVIEW

**Comment by mortenbra** [comment]
Hi, I've created a code standards document under /doc/coding_standards.txt. Please adjust your code with respect to l_returnvalue usage, author initials and date format in the comment block, as per the guidelines.

**Comment by mjhasbach** [comment]
@mortenbra sorry about that. The requested revisions have been made.

**Comment by mortenbra** [comment]
I don't think this will work if the user's current NLS setting uses a comma instead of a dot as the decimal separator? You should get the current decimal separator by calling get_nls_decimal_separator (already in this package) instead of hardcoding the separator.

**Comment by mjhasbach** [comment]
Good point. I went with the simpler approach of checking the string for non-numeric characters. The function will work now regardless of NLS settings.

**Pull request merged**
